
---
- name: Install Apache and Upload Web page
  hosts: Cent7
  become: yes

  vars:
          src_file: ./mywebSite/index.html
          dest_file: /var/www/html

  tasks:
          - name: Install Apache Web Server
            yum: name=httpd state=latest

          - name: Copy MyHomePage to Server
            copy: src={{ src_file }} dest={{ dest_file }} mode=0555
            notify: Restart Apache

          - name: Start WebServer and make it enable on boot
            service: name=httpd state=started enabled=yes

  handlers:
          - name: Restart Apache
            service: name=httpd state=restarted
